#define COBJMACROS
#include <windows.h>
#include "WebView2.h"
static HWND hwnd;static ICoreWebView2Controller *controller;static ICoreWebView2 *web;
static HRESULT STDMETHODCALLTYPE qi(void *o,REFIID i,void **p){*p=o;return S_OK;}
static ULONG STDMETHODCALLTYPE ref(void *o){return 2;}
static void result(char *step,HRESULT hr){char b[180];DWORD n;wsprintfA(b,"%s: %08lx\r\n",step,hr);WriteFile(GetStdHandle(STD_OUTPUT_HANDLE),b,lstrlenA(b),&n,0);}
static HRESULT STDMETHODCALLTYPE ready(ICoreWebView2CreateCoreWebView2ControllerCompletedHandler *h,HRESULT hr,ICoreWebView2Controller *c){result("controller",hr);if(FAILED(hr))return hr;controller=c;ICoreWebView2Controller_AddRef(c);RECT r;GetClientRect(hwnd,&r);ICoreWebView2Controller_put_Bounds(c,r);ICoreWebView2Controller_put_IsVisible(c,TRUE);ICoreWebView2Controller_get_CoreWebView2(c,&web);result("navigate",ICoreWebView2_NavigateToString(web,L"<!doctype html><html><body style='background:#123d55;color:white;font:28px sans-serif'><h1>WebView2 display test</h1><p>This is a minimal native host, outside Inventor.</p><button onclick='this.innerText=\"Clicked successfully\"'>Click to test input</button></body></html>"));return S_OK;}
static ICoreWebView2CreateCoreWebView2ControllerCompletedHandlerVtbl cv={(void*)qi,(void*)ref,(void*)ref,ready};static ICoreWebView2CreateCoreWebView2ControllerCompletedHandler cb={&cv};
static HRESULT STDMETHODCALLTYPE envready(ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler *h,HRESULT hr,ICoreWebView2Environment *e){result("environment",hr);if(FAILED(hr))return hr;return ICoreWebView2Environment_CreateCoreWebView2Controller(e,hwnd,&cb);}
static ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandlerVtbl ev={(void*)qi,(void*)ref,(void*)ref,envready};static ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler eb={&ev};
static LRESULT CALLBACK proc(HWND h,UINT m,WPARAM w,LPARAM l){if(m==WM_SIZE&&controller){RECT r;GetClientRect(h,&r);ICoreWebView2Controller_put_Bounds(controller,r);}if(m==WM_DESTROY){if(controller)ICoreWebView2Controller_Close(controller);PostQuitMessage(0);return 0;}return DefWindowProcW(h,m,w,l);}
void mainCRTStartup(void){CoInitializeEx(0,COINIT_APARTMENTTHREADED);static WCHAR flags[2048];if(GetEnvironmentVariableW(L"HOME_TEST_FLAGS",flags,2048))SetEnvironmentVariableW(L"WEBVIEW2_ADDITIONAL_BROWSER_ARGUMENTS",flags);WNDCLASSW wc={0};wc.lpfnWndProc=proc;wc.hInstance=GetModuleHandleW(0);wc.lpszClassName=L"MinimalWebView";wc.hbrBackground=(HBRUSH)(COLOR_WINDOW+1);wc.hCursor=LoadCursorW(0,IDC_ARROW);RegisterClassW(&wc);hwnd=CreateWindowW(wc.lpszClassName,L"WebView2 isolated display test",WS_OVERLAPPEDWINDOW|WS_VISIBLE,100,100,1000,700,0,0,wc.hInstance,0);HMODULE dll=LoadLibraryW(L"C:\\ResearchUI\\WebView2Loader.dll");typedef HRESULT(WINAPI *Create)(LPCWSTR,LPCWSTR,ICoreWebView2EnvironmentOptions*,ICoreWebView2CreateCoreWebView2EnvironmentCompletedHandler*);Create fn=(Create)GetProcAddress(dll,"CreateCoreWebView2EnvironmentWithOptions");if(!fn)ExitProcess(3);result("start",fn(0,L"C:\\ResearchUI\\MinimalCache",0,&eb));MSG msg;while(GetMessageW(&msg,0,0,0)>0){TranslateMessage(&msg);DispatchMessageW(&msg);}ExitProcess(0);}
