#include <windows.h>
#include <delayimp.h>
static HANDLE logf;static LONG lines;
static void logcall(char *name,HDC dc,int x,int y,int w,int h,BOOL ok){if(InterlockedIncrement(&lines)>300)return;char b[300];DWORD n;wsprintfA(b,"%s dc=%p hwnd=%p xy=%d,%d size=%d,%d result=%d err=%lu\r\n",name,dc,WindowFromDC(dc),x,y,w,h,ok,GetLastError());WriteFile(logf,b,lstrlenA(b),&n,0);}
static BOOL WINAPI blt(HDC d,int x,int y,int w,int h,HDC s,int sx,int sy,DWORD op){BOOL r=BitBlt(d,x,y,w,h,s,sx,sy,op);logcall("BitBlt",d,x,y,w,h,r);return r;}
static int WINAPI dib(HDC d,int x,int y,int w,int h,int sx,int sy,int sw,int sh,const void *bits,const BITMAPINFO *bmi,UINT use,DWORD op){int r=StretchDIBits(d,x,y,w,h,sx,sy,sw,sh,bits,bmi,use,op);logcall("StretchDIBits",d,x,y,w,h,r);return r;}
static BOOL WINAPI ulw(HWND h,HDC d,const POINT *p,const SIZE *s,HDC src,const POINT *sp,COLORREF c,const BLENDFUNCTION *b,DWORD f){BOOL r=UpdateLayeredWindow(h,d,p,s,src,sp,c,b,f);logcall("UpdateLayeredWindow",src,0,0,s?s->cx:0,s?s->cy:0,r);return r;}
static BOOL WINAPI alpha(HDC d,int x,int y,int w,int h,HDC src,int sx,int sy,int sw,int sh,BLENDFUNCTION b){BOOL r=GdiAlphaBlend(d,x,y,w,h,src,sx,sy,sw,sh,b);logcall("GdiAlphaBlend",d,x,y,w,h,r);return r;}
static HDC WINAPI getdc(HWND h){HDC dc=GetDC(h);char b[160];DWORD n;wsprintfA(b,"GetDC hwnd=%p dc=%p err=%lu\r\n",h,dc,GetLastError());WriteFile(logf,b,lstrlenA(b),&n,0);return dc;}
static void slot(ULONG_PTR *p,void *fn){DWORD old;if(*p==(ULONG_PTR)fn)return;if(VirtualProtect(p,sizeof(*p),PAGE_READWRITE,&old)){*p=(ULONG_PTR)fn;DWORD n;WriteFile(logf,"patched slot\r\n",14,&n,0);VirtualProtect(p,sizeof(*p),old,&old);}}
static void table(BYTE *base,IMAGE_THUNK_DATA *names,IMAGE_THUNK_DATA *iat){for(;names->u1.AddressOfData;names++,iat++){if(IMAGE_SNAP_BY_ORDINAL(names->u1.Ordinal))continue;char *s=(char*)((IMAGE_IMPORT_BY_NAME*)(base+names->u1.AddressOfData))->Name;if(!lstrcmpA(s,"GetDC"))slot(&iat->u1.Function,getdc);if(!lstrcmpA(s,"GdiAlphaBlend"))slot(&iat->u1.Function,alpha);if(!lstrcmpA(s,"BitBlt"))slot(&iat->u1.Function,blt);if(!lstrcmpA(s,"StretchDIBits"))slot(&iat->u1.Function,dib);if(!lstrcmpA(s,"UpdateLayeredWindow"))slot(&iat->u1.Function,ulw);}}
static DWORD WINAPI worker(void *v){WCHAR path[180];wsprintfW(path,L"C:\\ResearchLicense\\present4-%lu.log",GetCurrentProcessId());logf=CreateFileW(path,GENERIC_WRITE,FILE_SHARE_READ,0,CREATE_ALWAYS,0,0);DWORD n;WriteFile(logf,"probe loaded\r\n",14,&n,0);for(int t=0;t<120;t++){BYTE *base=(BYTE*)GetModuleHandleW(L"msedge.dll");if(base){IMAGE_NT_HEADERS *nt=(void*)(base+((IMAGE_DOS_HEADER*)base)->e_lfanew);DWORD rva=nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_IMPORT].VirtualAddress;if(rva){IMAGE_IMPORT_DESCRIPTOR *i=(void*)(base+rva);for(;i->Name;i++)if(i->OriginalFirstThunk)table(base,(void*)(base+i->OriginalFirstThunk),(void*)(base+i->FirstThunk));}rva=nt->OptionalHeader.DataDirectory[IMAGE_DIRECTORY_ENTRY_DELAY_IMPORT].VirtualAddress;if(rva){ImgDelayDescr *i=(void*)(base+rva);for(;i->rvaDLLName;i++)table(base,(void*)(base+i->rvaINT),(void*)(base+i->rvaIAT));}}Sleep(500);}return 0;}
BOOL WINAPI DllMain(HINSTANCE h,DWORD r,void *v){if(r==DLL_PROCESS_ATTACH){DisableThreadLibraryCalls(h);CreateThread(0,0,worker,0,0,0);}return TRUE;}
